# Generated by Django 3.2.9 on 2021-12-05 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Genre')),
                ('slug', models.SlugField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('slug', models.SlugField(max_length=100)),
                ('coverImage', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('author', models.CharField(max_length=100, verbose_name='Author')),
                ('description', models.TextField(verbose_name='Description')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='pdf/')),
                ('fiction_books', models.BooleanField(default=False)),
                ('nonfiction_books', models.BooleanField(default=False)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libymaxapp.genre')),
            ],
        ),
    ]
