# Generated by Django 3.2.9 on 2021-12-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libymaxapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bestseller_books',
            field=models.BooleanField(default=False),
        ),
    ]
