# Generated by Django 3.2.9 on 2021-12-05 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libymaxapp', '0004_remove_book_bestseller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='bestseller_books',
            new_name='bestseller',
        ),
    ]
