# Generated by Django 3.2.9 on 2021-12-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libymaxapp', '0005_rename_bestseller_books_book_bestseller'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_book', models.CharField(max_length=100, verbose_name='Name of Book')),
            ],
        ),
    ]
